---
- hosts: all
  vars:
  - aaa2: "{{aaa|default('AA')}}"
  - bbb2: "{{bbb|default('BB')}}"
  - ccc2: "{{ccc|default('CC')}}"
  tasks:
  - name: Wait for SSH to come up.
    local_action: wait_for host=0.0.0.0 port=22 delay=60 timeout=320 state=started
  - name: PrintSomething
    debug: var=aaa2
  - name: PrintSomething
    debug: var=bbb2
  - name: PrintSomething
    debug: var=ccc2
